"""Proof-of-advantage report (Markdown) generated from ``results.json``.

The report states plainly what the evidence is and is not. Backtests are
never presented as proof of live profitability; synthetic data and
unmeasured (prior) latency are flagged at the top of the document.
"""

from __future__ import annotations

import json
from pathlib import Path


def _f(x, nd: int = 2) -> str:
    if x is None:
        return "n/a"
    if isinstance(x, float):
        if x != x:
            return "n/a"
        return f"{x:,.{nd}f}"
    return str(x)


def _ci(v) -> str:
    if not v or v[0] is None:
        return "n/a"
    return f"[{_f(v[0])}, {_f(v[1])}]"


def render(results: dict, reproduce_cmd: str = "") -> str:
    meta = results["meta"]
    ds = meta["dataset"]
    synthetic = ds.get("data_kind") == "synthetic"
    lat = ds.get("latency", {})
    L: list[str] = []
    title = "APEX MIND - CVIFA Evaluation Report"
    if synthetic:
        title += " - SYNTHETIC DATA (METHODOLOGY VALIDATION ONLY)"
    L += [f"# {title}", ""]
    banners = []
    if synthetic:
        banners.append("**SYNTHETIC DATA.** Generated by `apexmind.data.synthetic` with a known, planted structure. "
                       "Nothing in this report is evidence about real markets or real profitability.")
    if lat.get("source", "").startswith("prior"):
        banners.append(f"**LATENCY NOT MEASURED.** Fills used a conservative prior ({lat.get('detail')}), not live "
                       "execution measurements. Results must be re-run once live latency samples exist.")
    banners.append("**BACKTEST ONLY.** Out-of-sample simulation is not proof of live profitability. Live deployment "
                   "requires passing exchange integration tests and continued live measurement.")
    for b in banners:
        L += [f"> {b}", ""]

    champ = results["champion"]
    L += ["## Verdict", ""]
    if champ.get("selected"):
        sel = champ["selected"]
        L += [f"- Selected (simplest credible) model: **{sel['model']}** with **{sel['mode']}** execution.",
              f"- Beats every simple baseline after costs (paired test, 5%): "
              f"**{'YES' if champ.get('beats_all_baselines_after_costs') else 'NO'}**.",
              f"- {champ['verdict']}."]
    else:
        L += [f"- **{champ['verdict']}.** No strategy should be deployed on this evidence."]
    L += [""]

    period = ds.get("period", {})
    L += ["## Data", "",
          f"- Period (UTC): {period.get('start_utc')} to {period.get('end_utc')} ({period.get('hours')} h)",
          f"- Data kind: {ds.get('data_kind')}; fingerprint `{ds.get('data_fingerprint')}`; sessions: {ds.get('sessions')}",
          f"- Rows (decision-grid samples): {ds.get('rows'):,}; valid fraction: {_f(period.get('valid_fraction'), 4)}",
          f"- Purge/embargo gap between windows: {meta.get('gap_s')} s", ""]
    L += ["### Instrument coverage", "", "| Lighter | Reference | Multiplier | Eligible | Reason |", "|---|---|---|---|---|"]
    for s, i in sorted(ds.get("instruments", {}).items()):
        L.append(f"| {s} | {i.get('ref_symbol') or '-'} | {i.get('price_multiplier')} | {i.get('eligible')} | {i.get('reason')} |")
    L += [""]
    L += ["### Data quality", "", "| Stream | Messages | Gaps | Disconnects | Max gap ms | Delay p50/p95 ms |",
          "|---|---|---|---|---|---|"]
    for k, q in sorted(meta.get("data_quality", {}).items()):
        L.append(f"| {k} | {q['messages']:,} | {q['gaps']} | {q['disconnects']} | {q['max_interarrival_ms']} | "
                 f"{q['delay_ms_p50']}/{q['delay_ms_p95']} |")
    L += [""]

    L += ["## Execution and cost assumptions", "",
          f"- Latency model: **{lat.get('source')}** ({lat.get('detail')}); p50 {lat.get('p50_ms')} ms, "
          f"p90 {lat.get('p90_ms')} ms, p99 {lat.get('p99_ms')} ms. Applied as decision-to-fill delay on the local "
          "timeline; independent draws for entry and exit.",
          "- Aggressive fills: walk the recorded Lighter book at the simulated fill instant for the label notional "
          f"(${ds.get('extra', {}).get('label_notional', 'see config')}); positions are never sized above it.",
          "- Passive fills: post-only at the touch at entry time; filled only when the tape trades through the price "
          "or exhausts the displayed queue ahead plus our size; cancels never improve queue position; no partial fills.",
          f"- Fees (taker, maker) per market: {json.dumps(ds.get('fees'))}",
          "- Funding: charged when a Lighter funding timestamp falls inside the holding period, at the rate observed then.",
          "- Thresholds and horizons are learned on a calibration window the model never trained on, using a "
          "cluster-robust lower confidence bound on realized net returns.", ""]

    L += ["## Folds (separate out-of-sample periods)", "", "| Fold | Fit | Calibration | Test |", "|---|---|---|---|"]
    for f in results["folds"]:
        L.append(f"| {f['index']} | {f['fit_start_utc'][:16]} - {f['fit_end_utc'][:16]} | "
                 f"{f['cal_start_utc'][:16]} - {f['cal_end_utc'][:16]} | {f['test_start_utc'][:16]} - {f['test_end_utc'][:16]} |")
    L += [""]

    eq0 = None
    for name, r in results["models"].items():
        for mode, mr in r["modes"].items():
            eq0 = eq0 or next(iter(mr["equity_scenarios"]))
    L += [f"## Model comparison (primary equity ${eq0})", "",
          "| Model | Exec | Signals | Executed | Rejected | Net bps (95% CI) | Gross bps | Fees bps | Funding bps | "
          "Slip bps | PF | Expectancy $ | Max DD | ES95 bps | Return |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for name, r in results["models"].items():
        if r.get("gates") and not r["modes"]["aggressive"]["per_fold"]:
            L.append(f"| {name} | - | gated out: {r['gates'][0].get('reason') or 'not justified'} "
                     f"(p={_f(r['gates'][0].get('p_value'), 3)}) | | | | | | | | | | | | |")
            continue
        for mode, mr in r["modes"].items():
            sc = mr["equity_scenarios"][eq0]
            t, e, o = sc["trades"], sc["equity"], sc["opportunities"]
            L.append(f"| {name} | {mode} | {o['signals']:,} | {o['executed']:,} | {o['rejected']:,} | "
                     f"{_f(t.get('mean_net_bps'))} {_ci(t.get('mean_net_bps_ci'))} | {_f(t.get('mean_gross_bps'))} | "
                     f"{_f(t.get('mean_fees_bps'))} | {_f(t.get('mean_funding_bps'), 3)} | "
                     f"{_f(t.get('mean_entry_slippage_bps'))} | {_f(t.get('profit_factor'))} | "
                     f"{_f(t.get('expectancy_usd'), 4)} | {_f(e.get('max_drawdown'), 4)} | "
                     f"{_f(t.get('expected_shortfall_95_bps'))} | {_f(e.get('total_return'), 4)} |")
    L += [""]

    L += ["### Small-account feasibility", "", "| Model | Exec | Initial $ | Executed | Final $ | Top rejection reasons |",
          "|---|---|---|---|---|---|"]
    for name, r in results["models"].items():
        for mode, mr in r["modes"].items():
            for e, sc in mr["equity_scenarios"].items():
                if e == eq0:
                    continue
                reasons = ", ".join(f"{k}: {v}" for k, v in list(sc["opportunities"]["reasons"].items())[:3])
                L.append(f"| {name} | {mode} | {e} | {sc['opportunities']['executed']} | "
                         f"{_f(sc['equity']['final_equity'], 4)} | {reasons or '-'} |")
    L += [""]

    L += ["## Results per out-of-sample period (aggressive execution)", "",
          "| Model | Fold | Trades | Net bps (95% CI) | PF | Fold return |", "|---|---|---|---|---|---|"]
    for name, r in results["models"].items():
        for f in r["modes"]["aggressive"]["per_fold"]:
            L.append(f"| {name} | {f['fold']} | {f.get('n_trades', 0)} | {_f(f.get('mean_net_bps'))} "
                     f"{_ci(f.get('mean_net_bps_ci'))} | {_f(f.get('profit_factor'))} | {_f(f.get('return'), 4)} |")
    L += [""]

    L += ["## Statistical comparisons", ""]
    for mode, c in results["comparisons"].items():
        L += [f"### {mode} execution ({c['periods']} periods)", ""]
        spa = c.get("spa_vs_no_trading", {})
        L.append(f"- Hansen SPA, H0 'no model beats not trading': p = {_f(spa.get('p_value'), 4)} "
                 f"(best: {spa.get('best_model')})")
        if "spa_vs_best_baseline" in c:
            s = c["spa_vs_best_baseline"]
            L.append(f"- Hansen SPA, H0 'no non-baseline model beats {s['benchmark']}': p = {_f(s['p_value'], 4)}")
        pbo = c.get("pbo", {})
        L.append(f"- Probability of backtest overfitting (CSCV): {_f(pbo.get('pbo'), 3)} over "
                 f"{pbo.get('n_combinations')} splits")
        L += ["", "| Model | Deflated Sharpe P(SR>SR0) | Per-period SR | vs baselines: mean diff (CI) p |", "|---|---|---|---|"]
        for m, d in c.get("deflated_sharpe", {}).items():
            pw = c["pairwise_vs_baselines"].get(m, {})
            diffs = "; ".join(f"{b}: {_f(v['mean'] * 1e4)}bps [{_f(v['lo'] * 1e4)}, {_f(v['hi'] * 1e4)}] "
                              f"p={_f(v['p_value'], 3)}" for b, v in pw.items())
            L.append(f"| {m} | {_f(d.get('dsr'), 3)} | {_f(d.get('sr'), 3)} | {diffs or '-'} |")
        L += [""]

    L += ["## Regime breakdown (selected or best model, aggressive)", ""]
    target = (champ.get("selected") or {}).get("model") or next(iter(results["models"]))
    mode = (champ.get("selected") or {}).get("mode", "aggressive")
    regs = results["models"][target]["modes"][mode]["equity_scenarios"][eq0].get("regimes", {})
    for col, rows in regs.items():
        L += [f"**{col}** ({target}/{mode})", "", "| Regime | Trades | Net bps | 95% CI |", "|---|---|---|---|"]
        for k, v in rows.items():
            L.append(f"| {k} | {v['n']} | {_f(v['mean_net_bps'])} | {_ci(v.get('ci_bps'))} |")
        L += [""]

    L += ["## Champion checks", ""]
    for k, v in champ.get("checks", {}).items():
        L.append(f"- `{k}`: {'; '.join(v)}")
    L += ["", "## Reproducibility", "",
          f"- Code: apexmind {meta['version']} @ `{meta['git']}`; config hash `{meta['config_hash']}`",
          f"- Results hash `{meta['results_hash']}`; trials counted for deflation: {meta['trials']}",
          f"- Runtime: {meta['elapsed_s']} s"]
    if reproduce_cmd:
        L += [f"- Reproduce: `{reproduce_cmd}`"]
    L += ["", "Every number above is derived from `results.json` in the same run directory; trades are in `trades.csv`.", ""]
    return "\n".join(L)


def write_report(run_dir: str | Path, reproduce_cmd: str = "") -> Path:
    run_dir = Path(run_dir)
    results = json.loads((run_dir / "results.json").read_text())
    out = run_dir / "report.md"
    out.write_text(render(results, reproduce_cmd))
    return out
